--liquibase formatted sql

--changeset 001:1
CREATE TABLE IF NOT EXISTS TEAM (
  ID NUMERIC(18) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  INITIALS VARCHAR(20) NOT NULL,
  GROUPS VARCHAR(5) NOT NULL,
  FLAG VARCHAR(10) NOT NULL
  PRIMARY KEY (ID)
);

--changeset 001:2
CREATE TABLE IF NOT EXISTS ROUND (
  ID NUMERIC(18) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  INITIAL_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  PRIMARY KEY (ID)
);

--changeset 001:3
CREATE TABLE IF NOT EXISTS MATCHES (
  ID NUMERIC(18) NOT NULL,
  ID_HOME_TEAM NUMERIC(18) NOT NULL,
  ID_VISITING_TEAM NUMERIC(18) NOT NULL,
  ID_ROUND NUMERIC(18) NOT NULL,
  GAME_DATE DATE NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_HOME_TEAM) REFERENCES TEAM (ID),
  FOREIGN KEY (ID_VISITING_TEAM) REFERENCES TEAM (ID),
  FOREIGN KEY (ID_ROUND) REFERENCES ROUND (ID)
);

--changeset 001:4
CREATE TABLE IF NOT EXISTS BET (
  ID NUMERIC(18) NOT NULL,
  contract_hash_code VARCHAR(1000) NOT NULL,
  ID_MATCH NUMERIC(18) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_MATCH) REFERENCES MATCHES (ID)
);

--changeset 001:5
CREATE TABLE IF NOT EXISTS "user" (
  ID NUMERIC(18) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  LAST_NAME VARCHAR(256) NOT NULL,
  NICK_NAME VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL,
  BLOCK_CHAIN_CODE VARCHAR(1000) NOT NULL,
  ROLE VARCHAR(50) VARCHAR NOT NULL,
  PRIMARY KEY (ID)
);

--changeset 001:6
CREATE TABLE IF NOT EXISTS USER_BET (
  ID NUMERIC(18) NOT NULL,
  ID_USER NUMERIC(18) NOT NULL,
  ID_BET NUMERIC(18) NOT NULL,
  GUESS_HOME_TEAM NUMERIC(6) NOT NULL,
  GUESS_VISITING_TEAM NUMERIC(6) NOT NULL,
  BET_MADE boolean NOT NULL,
  BET_DATE DATE NOT NULL,
  BET_MADE_DATE DATE NOT NULL,
  DISCOUNT_FROM_WALLET boolean NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_USER) REFERENCES "user" (ID),
  FOREIGN KEY (ID_BET) REFERENCES BET (ID)
);

--changeset 001:7
CREATE SEQUENCE IF NOT EXISTS BET_SEQ INCREMENT BY 1 OWNED BY BET.ID

--changeset 001:8
CREATE SEQUENCE IF NOT EXISTS MATCHES_SEQ INCREMENT BY 1 OWNED BY MATCHES.ID

--changeset 001:9
CREATE SEQUENCE IF NOT EXISTS USER_SEQ INCREMENT BY 1 OWNED BY "user".ID

--changeset 001:10
CREATE SEQUENCE IF NOT EXISTS USER_BET_SEQ INCREMENT BY 1 OWNED BY USER_BET.ID

--changeset 001:11
CREATE SEQUENCE IF NOT EXISTS TEAM_SEQ INCREMENT BY 1 OWNED BY TEAM.ID

--changeset 001:12
CREATE SEQUENCE IF NOT EXISTS ROUND_SEQ INCREMENT BY 1 OWNED BY ROUND.ID

--changeset 001:13
INSERT INTO "user" (ID, NAME, LAST_NAME, NICK_NAME, EMAIL, BLOCK_CHAIN_CODE, ROLE) VALUES (1, 'Mateus', 'Teixeira', 'mateus.teixeira', 'mateus.teixeira@db1.com.br', 'mateus.teixeira', 'ROLE_ADMIN');
